# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: python:3.6.8
        working_dir: '/root/'
        environment:
          TZ: "Asia/Tokyo"
          PYTHONDONTWRITEBYTECODE: 1

      - image: mongo:4.2
        environment:
          MONGO_INITDB_ROOT_USERNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: admin
          TZ: "Asia/Tokyo"
        command: --auth

    working_directory: ~/EDMAN
    branches:
      only:
        - develop

    steps:
      - checkout

      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.6.1

      - run:
          name: Wait for MongoDB
          command: dockerize -wait tcp://localhost:27017 -timeout 1m

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            source ./venv/bin/activate
            python --version
            pip install -U pip
            pip install -U setuptools
            pip install sphinx
            pip install pytest
            pip install ~/EDMAN/
          working_directory: ~/

      - run:
          name: execute tests
          command: |
            source ~/venv/bin/activate
            mkdir ~/test-reports
            pytest --junitxml=~/test-reports/junit.xml
          working_directory: ~/EDMAN/tests

      - run:
          name: make docs
          command: |
            source ~/venv/bin/activate
            mkdir ~/docs
            sphinx-apidoc -f -o ./ ~/EDMAN/edman/
            make html
            cp -r _build/html ~/docs/
          working_directory: ~/EDMAN/docs

      - run:
          name: make docs repo
          command: |
            touch .nojekyll
            ls -la
            git config user.email "310414+ryde@users.noreply.github.com"
            git config user.name "circleci"
            git init
            git add .
            git commit -m "apidoc html renew"
            git remote -v
            git remote set-url origin git@github.com:yuskyamada/EDMAN.git
            git push -f origin master:gh-pages
          working_directory: ~/docs

      - store_artifacts:
          path: ~/test-reports
          destination: ~/test-reports

      - store_artifacts:
          path: ~/docs/html
