# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '2023.5.10.7.dev0+g4448531.d20230510'
__version_tuple__ = version_tuple = (2023, 5, 10, 7, 'dev0', 'g4448531.d20230510')
