# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '2022.4.14.dev113+g0d9bc6b.d20230510'
__version_tuple__ = version_tuple = (2022, 4, 14, 'dev113', 'g0d9bc6b.d20230510')
