# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '2022.4.14.dev110+g5354b3e.d20230510'
__version_tuple__ = version_tuple = (2022, 4, 14, 'dev110', 'g5354b3e.d20230510')
