name: edman Unittest

on:
  push:
    branches: [ develop ]

jobs:
  edman unittest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mongodb-version: [ '5.0' ]

    steps:
      - name: setup
      - uses: actions/checkout@v3

      - name: setup python and sources
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          check-latest: true
      - run: python -m venv venv
      - run: source ./venv/bin/activate
      - run: pip install -U pip setuptools
      - run: pip install sphinx pytest
      - run: pip install ./edman/
      - run: mkdir ./edman/test-reports
      - run: cp ./edman/edman/tests/ini/test_db.ini.sample ./edman/edman/tests/ini/test_db.ini

      - name: setup DB
      - uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
          mongodb-username: admin
          mongodb-password: admin
          mongodb-db: admin

      - name: run unittest
      - run: cd ./edman
      - run: pytest --junitxml=test-reports/junit.xml
